using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Text;
using System.IO;
public partial class MoviePage : System.Web.UI.Page
{
    private readonly IArticleService _ArticleService;
    private DataTable dt;

    public MoviePage()
    {
        _ArticleService = new ArticleService(new ConnDB());
    }


    protected void Page_Load(object sender, EventArgs e)
    {
        GridView_喜劇.DataSource = _ArticleService.GetArticleByType("喜劇片");
        GridView_喜劇.DataBind();

        GridView_動作.DataSource = _ArticleService.GetArticleByType("動作片");
        GridView_動作.DataBind();

        GridView_愛情.DataSource = _ArticleService.GetArticleByType("愛情片");
        GridView_愛情.DataBind();



        //GridView_喜劇.AutoGenerateDeleteButton = true;
        //GridView_動作.AutoGenerateDeleteButton = true;
        //GridView_愛情.AutoGenerateDeleteButton = true;

        //GridView_喜劇.DataBind();
        //GridView_動作.DataBind();
        //GridView_愛情.DataBind();


        #region 暫時取消
        //try
        //{
        //    string ID = Session["帳號"].ToString();
        //    ConnDB conns = new ConnDB();
        //    DataTable dt = new DataTable();
        //    string sqlStr = "Select * from 會員基本資料表 where 帳號 ='" + ID + "' ";
        //    dt = conns.LoadTable_SQL(sqlStr, "");
        //    string Max = dt.Rows[0]["權限"].ToString();

        //    if (Max == "1")
        //    {
        //        GridView_喜劇.AutoGenerateDeleteButton = true;
        //        GridView_動作.AutoGenerateDeleteButton = true;
        //        GridView_愛情.AutoGenerateDeleteButton = true;
        //        btnMax.Visible = true;
        //        GridView_喜劇.DataBind();
        //        GridView_動作.DataBind();
        //        GridView_愛情.DataBind();
        //    }
        //}
        //catch
        //{

        //}
        #endregion
    }
   
 
}